app:
  jwtExpirationInMs: 604800000
  jwtSecret: JWTSuperSecretKey
  file.export:
    kiemhong: KIEM_HONG__
    dathang: DAT_HANG__
    pa: PHUONG_AN__
    cntp: CNTP__
    thongke: THONG_KE__

server.port: 38081

spring:
  output:
    ansi:
      enabled: ALWAYS
  datasource:
#    driver-class-name: com.mysql.jdbc.Driver  # old class-driver
    driver-class-name: com.mysql.cj.jdbc.Driver # newer
    url: jdbc:mysql://localhost:3306/px_tool12?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: root
    hikari:
      idle-timeout: 10000
      minimum-idle: 10
      connection-timeout: 30000
      maximum-pool-size: 100
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        connection:
          characterEncoding: utf-8
          charSet: utf-8
          useUnicode: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: false
        show_sql: false
        globally_quoted_identifiers: true
        generate-ddl: true

#logging.level.org.hibernate.SQL: DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder: TRACE

## MULTIPART (MultipartProperties)
# Enable multipart uploads
spring.servlet.multipart.enabled: true
# Threshold after which files are written to disk.
spring.servlet.multipart.file-size-threshold: 2KB
# Max file size.
spring.servlet.multipart.max-file-size: 20MB
# Max Request Size
spring.servlet.multipart.max-request-size: 22MB